---
# Copyright 2018, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in witing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Ensure deploy host is running
  hosts: vm_hosts
  gather_facts: "{{ gather_facts | default(true) }}"
  tags:
    - fetch-osa-inv
  tasks:
    - name: Set deploy host to running state
      virt:
        name: "{{ hostvars[item]['server_hostname'] }}"
        state: running
      when:
        - hostvars[item]['server_vm'] | default(false) | bool
      with_items: "{{ groups['deploy_hosts'] }}"

    - name: Wait until deploy host is running
      virt:
        command: status
        name: "{{ hostvars[item]['server_hostname'] }}"
      connection: local
      register: vm_info
      until: vm_info.status == 'running'
      retries: 100
      delay: 10
      when:
        - hostvars[item]['server_vm'] | default(false) | bool
      with_items: "{{ groups['deploy_hosts'] }}"

- name: Gather OSA inventory file
  hosts: deploy_hosts
  gather_facts: "{{ gather_facts | default(true) }}"
  tags:
    - fetch-osa-inv
  tasks:
    - name: Copy OSA inventory file
      fetch:
        src: /etc/openstack_deploy/openstack_inventory.json
        dest: /tmp/
        flat: yes

- name: Generate OSA INV load script
  hosts: vm_hosts
  gather_facts: "{{ gather_facts | default(true) }}"
  tags:
    - fetch-osa-inv
  tasks:
    - name: Write OSA INV load script
      copy:
        dest: /tmp/osa_inv.sh
        mode: 0744
        content: |
          #!/bin/bash
          cat /tmp/openstack_inventory.json
